### PR TITLE
Fix did issuer encoding

### LINKED ISSUE #11: Policy values aren't encoded
Meaning it'll produce an invalid DID when including a field that contains a character not supported by the DID spec. Or, if it contains a double colon (it'll make the did:x509 string invalid);

```
method-specific-id = *( *idchar ":" ) 1*idchar
idchar             = ALPHA / DIGIT / "." / "-" / "_" / pct-encoded
pct-encoded        = "%" HEXDIG HEXDIG
```

### PR DESCRIPTION
**Pull request by stevenvegt**
Replaced the url.PathEncode with custom percent encoder.
Fixes #11

### CODE REVIEW

File: did_x509/did_x509.go [hunk 1]
```diff
@@ -49,9 +51,28 @@ func CreateDid(signingCert, caCert *x509.Certificate, subjectAttributes []x509_c
...
 	return formattedDid, err
 }
+
+// PercentEncode encodes a string using percent encoding.
+// we can not use url.PathEscape because it does not escape : $ & + = : @ characters.
+// See https://github.com/golang/go/issues/27559#issuecomment-449652574
+func PercentEncode(input string) string {
+	var encoded strings.Builder
+	for _, r := range input {
+		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '-' || r == '_' || r == '.' || r == '~' {
```
Comment (reinkrul) [inline did_x509/did_x509.go:61]: I don't believe `~` is allowed in DIDs: https://www.w3.org/TR/did-core/#did-syntax

File: did_x509/did_x509.go [hunk 2]
```diff
@@ -49,9 +51,28 @@ func CreateDid(signingCert, caCert *x509.Certificate, subjectAttributes []x509_c
 	formattedDid, err := FormatDid(caCert, policies...)
 	return formattedDid, err
 }
+
+// PercentEncode encodes a string using percent encoding.
+// we can not use url.PathEscape because it does not escape : $ & + = : @ characters.
+// See https://github.com/golang/go/issues/27559#issuecomment-449652574
+func PercentEncode(input string) string {
```
Comment (reinkrul) [inline did_x509/did_x509.go:58]: at line 47, there's an ignored `err` variable. Maybe you can check it, while you're at it?

**Review by reinkrul — CHANGES_REQUESTED** [review]

**Review by reinkrul — APPROVED** [review]
